### PR TITLE
Include timecop gem for development, test and demo only

### LINKED ISSUE #309: Nomethoderror: undefined method `return' for Timecop:Class when running `db:reset`
Stacktrace:
```
stderr: rake aborted!
NoMethodError: undefined method `return' for Timecop:Class
/home/osttutor/src/tutor-913f30c/config/initializers/timecop.rb:18:in `load_time'
/home/osttutor/src/tutor-913f30c/config/initializers/timecop.rb:24:in `<top (required)>'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:652:in `block in load_config_initializer'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/notifications.rb:166:in `instrument'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:651:in `load_config_initializer'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:615:in `each'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:615:in `block in <class:Engine>'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `each'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `tsort_each_child'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
/home/osttutor/src/tutor-913f30c/config/environment.rb:19:in `<top (required)>'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/application.rb:328:in `require_environment!'
/home/osttutor/src/tutor-913f30c/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/application.rb:443:in `block in run_tasks_blocks'
Tasks: TOP => db:reset => environment
(See full trace by running task with --trace)
```

### PR DESCRIPTION
**Pull request by lakshmivyas**
Optional groups are available in the impending bundler 1.10 release.

Closes #309.

### CODE REVIEW

**Comment by lakshmivyas** [comment]
@jpslav - This one is ready for review.   (Needed for deployment).

**Comment by Dantemss** [comment]
An alternative would be to put timecop in the general group with `require: false` and then only require/do stuff with it in the initializer if `enable_timecop` is true.

**Comment by lakshmivyas** [comment]
@Dantemss - JP and I discussed this.   JP found it to be safer not have timecop available for use on non demo servers.

**Comment by jpslav** [comment]
timecop needs to be available in development and test and demo.  So maybe a better way to do this is:

```ruby
group :development, :test do
  # normal development & test gems without timecop listed.
end

group :development, :test, :demo do
  gem 'timecop'
end
```

And then in Travis we go back to the old way of saying `bundler_args: --without production --retry=6`, and then in real production we say `--without demo test demo`, and on the demo servers we say `--without development test`.

And then we don't need the new version of bundler.

**Comment by lakshmivyas** [comment]
sounds simple and great :)  Can someone else take this PR over and test it out?

**Comment by jpslav** [comment]
@karenc can you take over this PR and make the changes like I mentioned above?  And then once this is done we'll need @cnuber to deal with https://github.com/openstax/tutor-deployment/issues/75

**Comment by karenc** [comment]
Is this ok?

**Pull request merged**
