### PR TITLE
Practice Widget

### PR DESCRIPTION
**Pull request by jpslav**
Adds API endpoints to access a practice widget with faked exercises.  I've added a rake task to set up a scenario to test the practice widget.  

After checking out this branch, `jpslav-s8-practice-widget`, run the following once:

`bundle install --without production`

Then every time you want to reset the practice widget scenario state, run:

`bundle exec rake db:drop db:migrate sprint:008pw`

The `sprint:008pw` task creates a user with username "student" and a course, then registers the "student" user as a student in the course.  It then creates an initial practice widget.  I did this so you could test just using the practice widget before needing to create a new one.  

The last line output from running the command above will look something like this:

```
Added 'student' user with a practice widget with 5 fake exercises.  Access it with GET /api/courses/1/practice.  Create a new one with a POST to the same URL.
```

As you can see, it gives you the endpoint to use.

Just like normal, the process after running the rake tasks is to start the server:

`bundle exec rails server`

Then go to `http://localhost:3001/accounts`, hit the "search" button, then click on the "student" username.  This will log you in.  If you navigate manually to `http://localhost:3001/api/courses/1/practice` you'll see the practice widget JSON (it looks exactly like a normal Task).

/cc @philschatz @pandafulmanda

### CODE REVIEW

**Comment by jpslav** [comment]
Heads up @philschatz @pandafulmanda, the practice widget APIs are ready to test in the server.

**Comment by pandafulmanda** [comment]
@jpslav thanks for the awesome instructions, trying this out now

**Comment by jpslav** [comment]
@pandafulmanda this PR has been updated to address the `SecurityTransgression` problem you encountered.  Before running `bundle exec rake db:drop db:migrate sprint:008pw` make sure to run `bundle` as updated one of the app's libraries.  Let me know how it goes.

**Comment by joemsak** [comment]
Looking okay from here!

**Comment by pandafulmanda** [comment]
yes this seems to be good =) sorry about the false alarm this morning

**Comment by philschatz** [comment]
Just wondering what is this waiting on (besides a rebase from master)?

**Comment by jpslav** [comment]
I'm working other stuff (the BigLearn integration) but I'll go ahead and merge it in.

**Pull request merged**
