### PR TITLE
If a page fails to map for some reason, skip it and don't explode

### PR DESCRIPTION
**Pull request by Dantemss**

### CODE REVIEW

**Comment by jpslav** [comment]
Do we need to know that it failed to load? (is this change hiding something important from devs and the content team?)

**Comment by Dantemss** [comment]
Hm good question. I will poke production and try to figure out why this is happening there.

**Comment by Dantemss** [comment]
I poked production and it turned out to be some old Content::Models::Map from old code... I recreated them all (never Content::Models::Map code maps intro pages, old code didn't).

**Comment by Dantemss** [comment]
I guess we can close this for now.

**Pull request closed without merging**
