### PR TITLE
Changes for the new content

### PR DESCRIPTION
**Pull request by Dantemss**
- Cleaned up the fragment code a bunch
- Accepts more than 1 exercise per feature
- Temporary solution for the sims

I'll let you test JP :)

### CODE REVIEW

**Comment by Dantemss** [comment]
Added a temporary solution for the sims; Phil requested that we leave the HTML as-is for now.

**Comment by Dantemss** [comment]
OK the sim code should work for the demo. Just need Alina's change to the sim tagging.

**Comment by Dantemss** [comment]
https://www.pivotaltracker.com/story/show/91897172

**Comment by jpslav** [comment]
Reviewed -- looks good.  @Dantemss let me know when unblocked :-)

**Comment by Dantemss** [comment]
@jpslav done

**Pull request merged**
