### PR TITLE
README updates, NewRelic example, Bullet configurable

### PR DESCRIPTION
**Pull request by jpslav**
@nathanstitt can you review to make sure I'm not lying in the README?

### CODE REVIEW

**Comment by nathanstitt** [comment]
+1 I think that reads well and has a bunch of additional details that'll be useful.  I like the mention of the `USE_REAL_BACKGROUND_JOBS` in particular, I'll have to play with that.

A tiny quibble might be that it's not really necessary to run the entire `:drop, :create, :migrate, :seed` sequence.  

`rake db:reset demo` is equivalent and a bit shorter.
http://edgeguides.rubyonrails.org/active_record_migrations.html#resetting-the-database

**Comment by lakshmivyas** [comment]
For deployment, we use db:schema:load.  Perhaps we should use the same thing here.
https://github.com/openstax/tutor-deployment/blob/master/tasks/add_demo_data.yml#L12

BTW, are there any changes required to deployment because of these recent changes?

**Comment by jpslav** [comment]
@lakshmivyas yeah I think the tutor demo task should be dropping the database, which db:schema:load is not doing (wonder how things have been working up through this point?).

**Comment by jpslav** [comment]
thanks @nathanstitt for pointing that out -- updated the PR

**Comment by lakshmivyas** [comment]
@jpslav - I can't find the link (and doing too many things to search properly) - but `db:schema:load` turned out to be ideal for our setup as the rails user does not have (and should not have) privileges to drop a database.

**Pull request merged**
