### PR TITLE
Big demo import for testing

### PR DESCRIPTION
**Pull request by nathanstitt**
Adds a new "auto_assign" config option and uses it to generate a course with 150 students in 5 periods.

It then creates:
 * 30 homework assignments with 50 steps
 * 30 homework assignments with 10 steps
 * 10 reading assignments with 5 sections
 * 10 reading assignments covering 10 sections

### CODE REVIEW

**Comment by nathanstitt** [comment]
@jpslav The threaded-import pr was based off of this one, so when you merged it it merged into this, not master. ;)

**Comment by jpslav** [comment]
(doh!)

**Comment by nathanstitt** [comment]
@cnuber this has been changed so it will no longer run the "large" import unless it's specially requested.  If you want to run it you can do so by running: `rake db:reset demo[large]`

**Comment by Dantemss** [comment]
Updated to fix the demo spec and to make travis use less processes.

**Pull request merged**
