### PR TITLE
Hide uncertain clues from the learning guide

### PR DESCRIPTION
**Pull request by Dantemss**
This does not handle "never hide a CLUE once it is displayed", though the rules from BL ensure that a CLUE is never hidden after 5 questions are answered.

### CODE REVIEW

**Comment by Dantemss** [comment]
This does not handle "never hide a CLUE once it is displayed", though the rules from BL ensure that a CLUE is never hidden after 5 questions are answered.

**Comment by Dantemss** [comment]
@lakshmivyas You should take a look at this take a look before Chris deploys

**Comment by jpslav** [comment]
Ok, I'm merging this.  @lakshmivyas you should still take a look so we can head off any problems early in the day.  @cnuber heads up that this is in (in case it has BL deployment ramifications, though I'm guessing LN's stuff is in place)

**Comment by lakshmivyas** [comment]
Looks great.  @Dantemss - Thanks so much. You rock :+1: .

**Pull request merged**
