### PR TITLE
Cache teacher dashboard

### PR DESCRIPTION
**Pull request by Dantemss**
- Cache the teacher dashboard stats in Redis
- Specs

### CODE REVIEW

**Comment by Dantemss** [comment]
First request takes about the same as before. Second request about 390ms (previously 525ms).

**Comment by Dantemss** [comment]
Cache expires when anyone in the period answers any exercise.
Cache duration is the default for now (90 minutes, set in application.rb). So it will always expire after 90 minutes (we could make it last forever instead if that would be better).

**Comment by Dantemss** [comment]
The only thing this PR does not do is warm the cache (so the first request to the dashboard will be a little slow but not toooo slow).

**Comment by jpslav** [comment]
@Dantemss I think the cache expiration can probably be longer.

**Pull request merged**
