### PR TITLE
CC stats now returns total counts so that the FE can calculate the different averages

### PR DESCRIPTION
**Pull request by Dantemss**
@darrenmason

- CC stats now returns total counts so that the FE can calculate the different averages
- Specs

refs openstax/tutor-js#971

### CODE REVIEW

**Comment by Dantemss** [comment]
See https://github.com/openstax/tutor-js/pull/971 to help you get started.

**Comment by jpslav** [comment]
Looks good to me.  @philschatz @Dantemss @darrenmason can coordinate on merging this when FE ready.

**Comment by Dantemss** [comment]
Ignore this PR for now...

**Comment by Dantemss** [comment]
I'm closing. Reopen if we decide we need https://github.com/openstax/tutor-js/pull/971

**Pull request closed without merging**
