### PR TITLE
moves external classes to /lib, resolves #494

### LINKED ISSUE #494: Move configurable classes from app to lib
Or else they will break when the code is reloaded in dev.

For example, the Biglearn client.

### PR DESCRIPTION
**Pull request by jpslav**

### CODE REVIEW

**Comment by jpslav** [comment]
Used explicit listing of `require` calls to handle load order dependencies.

**Comment by jpslav** [comment]
@Dantemss please review.

**Comment by Dantemss** [comment]
Eww can I try to fix this mess of requires instead? :)

**Comment by Dantemss** [comment]
IMO the `requires.rb` should be renamed to the "fake gem" names (biglearn.rb etc)
The `requires.rb` should only require the "fake_gem_name/v1"
The `v1.rb's` should require the other files as appropriate.

**Comment by jpslav** [comment]
That would be fine.

**Comment by jpslav** [comment]
How's that @Dantemss?

**Comment by Dantemss** [comment]
Not sure I like the requires in a .each but it's way better I think

**Comment by jpslav** [comment]
Fixed.

**Pull request merged**
