### PR TITLE
Timecop

### PR DESCRIPTION
**Pull request by Dantemss**
- Switched Rails cache store to Redis
- Added settings store
- Added timecop logic to freeze time for all processes

### CODE REVIEW

**Comment by jpslav** [comment]
Looking nice. Pls add redis host port etc as secrets.  Also in anticipation of shared redis instance later can we scope the key names under a secret name (later tutor-production) or (tutor-stage). Change timecop to use travel instead of freeze. This will require setting the travel time and setting the time that travel time was set. Then when you travel you use both those values and time.now to travel to the right time.  Sorry reviewing from phone so this is short.

**Comment by lakshmivyas** [comment]
Shared instance may be sooner than later ;) :)

**Comment by Dantemss** [comment]
Do you expect that different environments (staging, production, demo?) will share the same redis instance?

**Comment by lakshmivyas** [comment]
I think the shared instance will be per envionment for scaled out configurations (think prod stage).  For dev/demo environments, we can think of having a shared instance.   If it doesn't cost us too much I think the best option is to have one instance per environment.  \cc @cnuber

**Comment by Dantemss** [comment]
Done except for admin views

**Comment by jpslav** [comment]
I think tutor-demo and the like will be on one box with redis on same box.  But stage and prod will be shared.

**Comment by lakshmivyas** [comment]
@jpslav - Given the issues we are having with BL, and the fact that we use redis on BL, bl admin (and for background jobs on our other apps), we might gain more benefit from a shared instance.   Same argument for local PG vs shared one.   We should discuss this sometime after alpha. \cc @cnuber .

The shared instances can just be a separate ec2 instance or managed ones (RDS, elasticache).

**Comment by jpslav** [comment]
I'm not overly excited by the idea of different instances for everything below staging. All on one seems ok at least for us for now.

**Pull request merged**
