### PR TITLE
Configure generators not to add stuff we don't normally mess with

### PR DESCRIPTION
**Pull request by joemsak**
Is the team cool with this

### CODE REVIEW

**Comment by Dantemss** [comment]
Not too sure about skipping routes and view specs, but definitely skip helpers and assets.

**Comment by joemsak** [comment]
Do we write view specs?

Skipping routes because the generator always writes them in a way that I never write them, and usually I've already added the route through TDD, as it's the undefined method of that named route in the view that comes up before the uninitialized constant FooController

**Comment by joemsak** [comment]
When I did `git clean -df spec/views` it deleted that entire folder so I'd wager that no we don't write them ;-P

**Comment by Dantemss** [comment]
Just because we don't doesn't mean we shouldn't :)
At least for the view stuff that is in the BE like the admin views...

**Comment by joemsak** [comment]
I use feature specs to cover the experience... personally have not ever messed with view specs, haven't met even advanced rails devs who do.. I'm not saying we should or shoudln't, but we don't and so why have the generator produce pending test files that the team isn't using?

**Comment by Dantemss** [comment]
In my view (HAH!) view specs are supposed to be simple, maybe just a check that the view doesn't blow up. And we do have one: https://github.com/openstax/tutor-server/blob/master/spec/views/webview/index.html.erb_spec.rb :)

**Comment by jpslav** [comment]
I'm ambivalent here.  I think because of our atypical file structure we don't really use generators all that much, so when we do I'm cool with just blowing away generated files that aren't needed.  If we don't use all these pieces and if generators might not work for our filesystem, do we really need them?

**Comment by jpslav** [comment]
Anyone else in @openstax/tutor-be-dev use generators and want to weigh in before we decide on this?

**Comment by Dantemss** [comment]
I do use generators btw, though admittedly most of the time I use the `rails g model name column:type` syntax, since I usually don't want views etc.

And then I have to move the files into the subsystem folders anyway...

**Comment by jpslav** [comment]
yeah that's how I use them too.

**Comment by joemsak** [comment]
Should I just close..

**Comment by Dantemss** [comment]
I found this lost branch and I think this is useful so I'm reopening...

**Pull request merged**
