### PR TITLE
CSRF protection

### PR DESCRIPTION
**Pull request by Dantemss**
- Added CSRF token to webview layout
- Added missing CSRF protection to API controllers

### CODE REVIEW

**Comment by Dantemss** [comment]
@philschatz @nathanstitt this requires ajax calls to send the CSRF token header (at least on non-get requests), as in: http://stackoverflow.com/a/8175979

**Comment by jpslav** [comment]
Looks good @Dantemss -- thanks!

**Comment by Dantemss** [comment]
For forms:

```html
<input name="authenticity_token" type="hidden" value="token_here" />
```

**Comment by jpslav** [comment]
@philschatz @nathanstitt let us know when you're ready for this to be merged.

**Pull request merged**
