### PR TITLE
/api/courses becomes /api/user/courses - filtered by user participation in courses

### PR DESCRIPTION
**Pull request by joemsak**

### CODE REVIEW

**Comment by philschatz** [comment]
@pandafulmanda @nathanstitt Can you make a `tutor-js` PR with corresponding code change?

**Comment by nathanstitt** [comment]
Sure @joemsak I don't see an update to the routes in the PR, is that coming or have I missed it?

The new route should be `/user/courses` though, correct?

**Comment by joemsak** [comment]
All is still WIP, team :) @nathanstitt @philschatz

**Comment by philschatz** [comment]
Yep, just making sure FE can make a corresponding PR

**Comment by joemsak** [comment]
:+1:

**Comment by joemsak** [comment]
I updated the routes so it's `/api/user/courses` @nathanstitt

**Comment by jpslav** [comment]
Double-check note to @pandafulmanda @nathanstitt -- with this PR `/api/courses` is gone and `/api/user/courses` is in its place.

**Comment by jpslav** [comment]
@philschatz @pandafulmanda @nathanstitt this looks good to me.  you guys can hit merge as soon as your corresponding PR is ready.

**Comment by nathanstitt** [comment]
@philschatz I've tested with the corresponding FE PR https://github.com/openstax/tutor-js/pull/409 and it loaded fine

**Comment by philschatz** [comment]
Does this mean period and role information are available on both `/user/courses` and `/user/courses/1`?

**Pull request merged**
