### PR TITLE
Sort page stats by page.book_location; Sort exercises by average step number

### PR DESCRIPTION
**Pull request by nathanstitt**
WIP because I'm not sure this is the correct order

### CODE REVIEW

**Comment by nathanstitt** [comment]
@pandafulmanda I don't think this worked correctly for you? Should we try another sort or just close it for now until we can pick it back up?

**Comment by Dantemss** [comment]
I think this could work (I know you can sort ruby hashes, but I feel bad doing that):

```rb
pages = page_hash.keys.sort_by{ |page| page.book_location }
pages.collect do |page|
  tasked_exercise = page_hash[page]
  generate_page_stats(page, tasked_exercises)
end
```

**Comment by Dantemss** [comment]
You prob just need to sort by `book_location` instead of by `number` (number resets for every chapter)

**Comment by Dantemss** [comment]
Ah I suppose it's fine, sort_by will give you an array of arrays... just use `book_location` instead of `number`.

**Comment by nathanstitt** [comment]
@pandafulmanda Do you remember what the order should be here?

**Comment by Dantemss** [comment]
@nathanstitt @pandafulmanda ready

**Comment by pandafulmanda** [comment]
:+1:  yayayayayaya

**Pull request merged**
