### PR TITLE
WIP: Lower # of students per period for demo courses

### PR DESCRIPTION
**Pull request by nathanstitt**
For testing by @cnuber.  

This reduces the time for a complete `rake db:reset demo` cycle from 11:57 to 6:50 minutes for me.

### CODE REVIEW

**Comment by Dantemss** [comment]
Hm are Kathi/Jason OK with this?

**Comment by nathanstitt** [comment]
Probably not, since they want a full roster of students for demoing.  This is for Chris to play with to see how much of an improvement it makes in import times.   I'm not planning on it being merged as-is

**Comment by Dantemss** [comment]
Close in my opinion, since the ruby/rails updates seem to have fixed the deployment issues...

**Comment by nathanstitt** [comment]
Yep, I agree!

**Pull request closed without merging**
