### PR TITLE
Student Identifier Fixes

### PR DESCRIPTION
**Pull request by Dantemss**
- Changed student_identifier unique index to apply only to records that are not deleted
- Added a check for duplicate student identifiers when undropping students
- Added error messages for duplicate student identifiers when updating and undropping students
- Specs

### CODE REVIEW

**Comment by Dantemss** [comment]
Might need FE... Possibly.

**Comment by nathanstitt** [comment]
yah, I think it will need some FE attention so it can handle the `student_identifier_has_already_been_taken` error on the additional endpoints.  I'll take a look to make sure

**Comment by jpslav** [comment]
Do we want to just not require student IDs to be unique and just flag them for teacher if there are dupes?

**Comment by jpslav** [comment]
Looks good otherwise.

**Comment by Dantemss** [comment]
@jpslav I suggested that but I believe Dr. Grim said that would just create instructor headaches.

**Comment by nathanstitt** [comment]
Yeah, I also updated the course settings FE so it's pretty easy for a teacher to change the student ID of a dropped student if there's duplicate errors when attempt to  un-drop.

**Pull request merged**
