### PR TITLE
Round II of styling for homepage

### PR DESCRIPTION
**Pull request by nathanstitt**
**Note**:  This hooks up the contact form to an action in static_pages#contact_form  The action currently only displays a message: "Sorry, delivering messages from the contact form is not yet implemented"

I took a poke around but didn't see any existing methods to send email.  If someone wants to give me a hint, I can go ahead and hook that up.

screen shot 2015-05-28 at 6 25 14 pm

### CODE REVIEW

**Comment by jpslav** [comment]
Pasting in full page image:

image

**Comment by jpslav** [comment]
Requests (@jason-holmes to bless):

1. Can the logo be vertically centered with the header buttons?  
2. Can the text of the SIGN IN button be the same size as the other header links and the text of all header buttons and links be vertically centered?
3. Can the "A Personalized Learning Experience" text be vertically centered with the video?
4. When you drag to make the browser wider that "A Personalized Learning Experience" text grows and shrinks oddly.
5. I like the original alternation between colored panels and white panels, and think having two white panels next to each other looks a little odd.  Can we maybe put the "OpenStax Tutor melds" text in a white section below the green section, then have the "What is it?" / "Who is behind it?" blurbs in a colored section?  That way we won't have two adjacent white sections.
6. Can the submit button styling match the "SIGN IN" styling? (even if different color, just saying non-rounded corners, all caps "SUBMIT", matching font sizes, etc).
7. When the page is made narrower, the sign in button text doesn't scale down like the other header text, the "what is it?" blurb gets too close to the "who is behind it?" blurb and the sponsor logos overlap their text descriptions (narrow view pasted below)
8. The "Need to contact us?" copy sounds a little off.  Maybe a "Interested in learning more?" or something is better (ask Dani?)

Narrow view:
image

**Comment by nathanstitt** [comment]
Vertical aligned top nav links and form submit now matches sign in:
screen shot 2015-05-29 at 9 27 18 am

**Comment by nathanstitt** [comment]
I'm not sure on the orange color when collapsed.  It might look better if it went full width, but that'll be difficult to accomplish with how the page is set up currently. 
screen shot 2015-05-29 at 9 40 37 am

**Comment by nathanstitt** [comment]
OK @jpslav here's what I've came up with:

Can the logo be vertically centered with the header buttons?
Can the text of the SIGN IN button be the same size as the other header links and the text of all header buttons and links be vertically centered?
 * Good call - done and done.

Can the "A Personalized Learning Experience" text be vertically centered with the video?
 * Not sure what you mean by "vertically centered"? do you mean equal space between each line and the video or something?
When you drag to make the browser wider that "A Personalized Learning Experience" text grows and shrinks oddly.
  * Yes, that's a side effect of how I specified the font size using `vw`  The font will shrink and grow to roughly fill it's container size.  That way no matter what screen size the person has the text will fill it.  It does appear kind of janky while resizing but that's ok since "regular" users won't be resizing their browser windows willy nilly.  They'll just visit and the text will fill the right side of the video.
I like the original alternation between colored panels and white panels, and think having two white panels next to each other looks a little odd. Can we maybe put the "OpenStax Tutor melds" text in a white section below the green section, then have the "What is it?" / "Who is behind it?" blurbs in a colored section? That way we won't have two adjacent white sections.
 * I did so but not sure if it's better or not.  Screenshot above.
Can the submit button styling match the "SIGN IN" styling? (even if different color, just saying non-rounded corners, all caps "SUBMIT", matching font sizes, etc).
 * Yes, I think that looks much nicer.
When the page is made narrower, the sign in button text doesn't scale down like the other header text, the "what is it?" blurb gets too close to the "who is behind it?" blurb and the sponsor logos overlap their text descriptions (narrow view pasted below)
 * I've removed all the text scaling since it's not needed now that we only have two links.
The "Need to contact us?" copy sounds a little off. Maybe a "Interested in learning more?" or something is better (ask Dani?)
 * That came from Kathi - so ?

**Comment by nathanstitt** [comment]
Collapsed view with orange who/what blocks:

screen shot 2015-05-29 at 10 08 31 am

**Comment by nathanstitt** [comment]
screen shot 2015-05-29 at 10 34 23 am

**Comment by nathanstitt** [comment]
screen shot 2015-05-29 at 10 39 14 am

**Comment by nathanstitt** [comment]
@jpslav ready for another round of review

**Comment by nathanstitt** [comment]
@jpslav Ok, give this version a shot.  Although it's not shown in this shot, on smaller resolutions the sponsor logo's are placed on top of their text.

screen shot 2015-05-29 at 12 58 31 pm

**Comment by nathanstitt** [comment]
Merging quick before @jpslav spots anymore misplaced pixels.

**Pull request merged**
