### PR TITLE
Return teacher objects in dashboard API instead of teacher_names

### PR DESCRIPTION
**Pull request by karenc**

### CODE REVIEW

**Comment by jpslav** [comment]
Looks great @karenc!

**Comment by karenc** [comment]
Added `role_id` to teachers in dashboard API.

**Comment by darrenmason** [comment]
encountered error on https://github.com/openstax/tutor-js/pull/827 regarding teacher delete api:

404 ActiveRecord::RecordNotFound in Api::V1::TeachersController#destroy
Couldn't find CourseMembership::Models::Teacher with 'id'=12

when role_id in dashboard teachers, used in DELETE /api/teachers/:role_id

**Comment by karenc** [comment]
@darrenmason the delete teacher API uses the teacher id, not the role id.

**Comment by darrenmason** [comment]
@karenc can we replace role id with teacher id?

**Comment by karenc** [comment]
@darrenmason Do you mean in this PR (the teacher object)?  The teacher id is the id field.

**Comment by darrenmason** [comment]
the goal is to be able to add/remove teacher using the teachers list.  Can I pass the id field to DELETE /api/teachers/:teacher_id ?

**Comment by karenc** [comment]
Yes that's right.

**Comment by darrenmason** [comment]
ok, thanks

**Comment by jpslav** [comment]
@darrenmason and @philschatz can merge when they are ready

**Pull request merged**
