### PR TITLE
add feature flags for response validation

### PR DESCRIPTION
**Pull request by nathanstitt**
Adds flag to disable completely and one to disable only the UI

### CODE REVIEW

**Comment by reedstrm** [comment]
Is there an issue for this, so  can see why we're disabling validation? (Normally not a thing I'm in favor of …)

**Comment by reedstrm** [comment]
Ahhh, I see - new, friendly name "response validation" rather than "gibberish/garbage detection" Got it.

**Comment by nathanstitt** [comment]
yep, that's just to unify the naming across the UI and the data model

**Comment by reedstrm** [comment]
A bit confusing on the backend, when 'validation' has so many other meanings.

**Comment by reedstrm** [comment]
Don't know why codecoverage is so wacko on this. Approved.

**Pull request merged**
