### PR TITLE
Return the full TOC including the book title

### PR DESCRIPTION
**Pull request by karenc**
The readings API (/api/courses/1/readings) for the sample book
(https://cnx.org/contents/7db9aa72-f815-4c3b-9cb6-d50cf5318b58@4.128)
has changed from:

```json
[
    {"id":"2",
     "title":"Forces and Newton's Laws of Motion",
     "type":"part",
     "chapter_section":[1],
     "children":[
        {"id":"1",
         "title":"Introduction",
         "type":"page",
         "chapter_section":[1,1]},
        {"id":"2",
         "title":"Force",
         "type":"page",
         "chapter_section":[1,2]},
        {"id":"3",
         "title":"Newton's First Law of Motion: Inertia",
         "type":"page",
         "chapter_section":[1,3]},
        {"id":"4",
         "title":"Newton's Second Law of Motion",
         "type":"page",
         "chapter_section":[1,4]},
        {"id":"5",
         "title":"Newton's Third Law of Motion",
         "type":"page",
         "chapter_section":[1,5]}]}]
```

to:

```json
[
    {"id":"1",
     "title":"Updated Tutor HS Physics Content - legacy",
     "type":"part",
     "children":[
        {"id":"2",
         "title":"Forces and Newton's Laws of Motion",
         "type":"part",
         "chapter_section":[1],
         "children":[
            {"id":"1",
             "title":"Introduction",
             "type":"page"
             ,"chapter_section":[1,1]},
            {"id":"2",
             "title":"Force",
             "type":"page",
             "chapter_section":[1,2]},
            {"id":"3",
             "title":"Newton's First Law of Motion: Inertia",
             "type":"page",
             "chapter_section":[1,3]},
            {"id":"4",
             "title":"Newton's Second Law of Motion",
             "type":"page",
             "chapter_section":[1,4]},
            {"id":"5",
             "title":"Newton's Third Law of Motion",
             "type":"page",
             "chapter_section":[1,5]}]}]}]
```

### CODE REVIEW

**Comment by jpslav** [comment]
@karenc -- why get rid of the outer array?  (in the future readings could be multiple books, and if FE already ok with the outer array let's just leave it)

**Comment by karenc** [comment]
Oh I see, I'll add the array back in

**Comment by karenc** [comment]
@jpslav ready for review

**Comment by jpslav** [comment]
@jivewise can hit the merge button when he's ready

**Pull request merged**
