### PR TITLE
Create performance report export with valid worksheet names

### PR DESCRIPTION
**Pull request by karenc**
Valid characters for Excel sheet names:

 - does not exceed 31 characters
 - does not contain : \ / ? * [ ]

### CODE REVIEW

**Comment by jpslav** [comment]
wunderbar!

**Comment by philschatz** [comment]
Should FE (and `tutor-server`) Error when the teacher tries to create/edit a Period name?


/cc @darrenmason, @nathanstitt?

**Comment by Fredasaurus** [comment]
Maybe I need context. Why would we create a scenario where something is editable, or looks to be, and then error?

**Comment by jpslav** [comment]
I think he's saying should we restrict the valid period names to be those that won't give errors when we export to Excel.  

The context is that Excel restricts what characters can be in worksheet names, and we use Period names for worksheet names.  This pull request (merged) replaces invalid Excel worksheet name characters with hyphens.  So using the exception example from this morning, a period name of "101 - 7:30AM  - Waldo" would lead to a worksheet name of "101 - 7-30AM  - Waldo"

**Comment by jpslav** [comment]
I'm in favor of not restricting period name characters to what Excel can handle, and just doing a search and replace like this PR does.

**Comment by philschatz** [comment]
thanks @jpslav! and it would cut off the period name after 31 characters (which might be a bit confusing). Would cutting it off at 31 characters introduce a new bug? ie does Excel allow multiple worksheets with the same name?

**Comment by Dantemss** [comment]
I don't think we ever intended period names to be that long...

**Comment by jpslav** [comment]
Yes we could be subject to another bug if people make period names that are the same for the first 31 characters (or that become the same when we substitute out illegal characters).  I doubt it will happen (I think our users will see rendering issues that encourage them to make the names shorter), but I will make an issue nonetheless.

**Pull request merged**
