### PR TITLE
Add chapter and section to cnx books and pages

### PR DESCRIPTION
**Pull request by joemsak**
Addresses #59 

- `#path` db attribute added to `Page` and `Book`
- `Import::Page` and `Import::Book` refactored for single responsibility in small functions
- `Import::Page` and `Import::Book` now construct paths based on presence of parent books and path variables

### CODE REVIEW

**Comment by Dantemss** [comment]
It's going in the right direction, I believe. Just keep in mind that the root Book is a special case (it's not included in the path), so you might need to check whether the parent_book is nil somewhere (that is the root) and handle that.

**Comment by Dantemss** [comment]
Also assuming parent_book is not nil, you don't need to check whether it responds to path, as it will always be either a Book or nil.

**Comment by joemsak** [comment]
Yep that’s handled by checking if parent_book responds to path (a crafty way of asking if it’s nil) and then path_index will be nil, too, because it hasn’t dropped into hash[‘contents’].each_with_index yet (where path_index starts getting passed in), so path will be set to a blank string

**Comment by Dantemss** [comment]
I see now :)

**Comment by jpslav** [comment]
@joemsak I'm an evil person and my delay on merging this PR means it is now very out of date (largely due to the fact that some of these files moved into a Content subsystem).  I'm going to need you to rebase / merge and bring it up to date.

**Pull request merged**
