### PR TITLE
need type in data heading for performance report to set different headings for external

### PR DESCRIPTION
**Pull request by pandafulmanda**
Is this allowed?

Wanted for openstax/tutor-js#477 so that there's a way to differentiate external heading from reading and homework heading and avoid linking to stats review

### CODE REVIEW

**Comment by jpslav** [comment]
Looks good to me :-)

**Comment by pandafulmanda** [comment]
dang it, fixing the spec for real

**Comment by jpslav** [comment]
just an order problem

**Comment by pandafulmanda** [comment]
YAY :cake:

**Pull request merged**
