### PR TITLE
[Wait for release after old scores are frozen] remove unused fields from performance api

### PR DESCRIPTION
**Pull request by nathanstitt**
specs need cleanup still

### CODE REVIEW

**Comment by Dantemss** [comment]
I am actually surprised is_extended and is_late are not used... don't we need these for some icons?
Oh is_late was never added to the representer huh?

**Comment by Dantemss** [comment]
Ah ok... the late work column makes is_late unnecessary... but the extension icon should still be there...

**Comment by nathanstitt** [comment]
is_extended can be determined by if the due_at field differs from the heading, and is_late wasn't ever used.  we may need to add that at some point but figured we can do that if needed

**Comment by Dantemss** [comment]
See comment on FE-side PR about freezing old scores first.

**Pull request merged**
