### PR TITLE
New meta description for Google search results

### PR DESCRIPTION
**Pull request by jpslav**

### CODE REVIEW

**Comment by CourtneyRay** [comment]
@kajalp What is the estimate for this going live?

**Comment by CourtneyRay** [comment]
@jpslav The new meta description and the old meta description appear to both be present in the HTML. I think the search engines are still pulling the old one. Can we remove? They appear as follows: 
<meta property="og:description" content="If you're piloting Tutor in your class or interested in trying it, visit us here. Our adaptive courseware creates personalized learning paths for every student.">
<meta name="Description" content="Personalized learning from a tutor that adapts to you.">

**Comment by CourtneyRay** [comment]
screen shot 2016-03-30 at 1 58 42 pm

**Comment by jpslav** [comment]
Ah, I changed the Facebook OpenGraph description and not the main description.  Will update.

**Comment by jpslav** [comment]
@CourtneyRay -- changed in https://github.com/openstax/tutor-server/pull/1041

**Comment by CourtneyRay** [comment]
@jpslav I'm still seeing the old description there, too: 
screen shot 2016-04-13 at 5 08 55 pm

**Comment by jpslav** [comment]
The code is merged, just depends on when gets released.  e.g. see
tutor-latest.openstax.org

**Pull request merged**
