### PR TITLE
changed API output of  from 4.2 to [4,2]

### PR DESCRIPTION
**Pull request by jpslav**

### CODE REVIEW

**Comment by jpslav** [comment]
@karenc please review; then @philschatz please merge when FE is ready for the change.

**Comment by karenc** [comment]
:+1:

**Comment by karenc** [comment]
Added chapter_section field to content_tags because the section information extracted from LO tags (in the exercises api) doesn't really match the section information we get in readings.  

For example, the readings api returns something like this:

```json
[{"id":2,"title":"Forces and Newton's Laws of Motion","type":"part","chapter_section":[1],"children":[
    {"id":1,"title":"Introduction","type":"page","chapter_section":[1,1]},
    {"id":2,"title":"Force","type":"page","chapter_section":[1,2]},
    {"id":3,"title":"Newton's First Law of Motion: Inertia","type":"page","chapter_section":[1,3]},
    {"id":4,"title":"Newton's Second Law of Motion","type":"page","chapter_section":[1,4]},
    {"id":5,"title":"Newton's Third Law of Motion","type":"page","chapter_section":[1,5]}]}]
```

The exercises api was returning something like this:

```
...
"tags":[{"id":"k12phys-ch04-s01-lo01","type":"lo","name":"Differentiate between force, net force and dynamics","chapter_section":[4,1]},
...
"tags":[{"id":"k12phys-ch04-s02-lo01","type":"lo","name":"Describe Newton's first law and friction a∝1ma∝1m","chapter_section":[4,2]},
...
```

This might be a data issue in the example book.  I don't really know.  My commit changes the exercises api to return:

```
...
"tags":[{"id":"k12phys-ch04-s01-lo01","type":"lo","name":"Differentiate between force, net force and dynamics","chapter_section":[1,2]},
...
"tags":[{"id":"k12phys-ch04-s02-lo01","type":"lo","name":"Describe Newton's first law and friction a∝1ma∝1m","chapter_section":[1,3]},
...

**Comment by jpslav** [comment]
@karenc can you remove your commit?  (maybe stash it off somewhere in case things change and we need it again).

**Comment by karenc** [comment]
Ok done

**Comment by jpslav** [comment]
@philschatz this PR is now ready; you say the word.

**Comment by karenc** [comment]
@jpslav the book doesn't seem to have the empty chapters you talked about so readings and exercises don't have matching chapter_section.  Could you look into it?

**Comment by jivewise** [comment]
Here's the front end PR: https://github.com/openstax/tutor-js/pull/192

**Pull request merged**
